### ISSUE TITLE
'config.h' file not found

### ISSUE THREAD

**Issue by gabegorelick** [ml1nk/node-scrypt#10]
I can successfully install `scrypt`, but can't install `@mlink/scrypt`. I have a working copy of node-gyp and all the prerequisites, as far as I know. 

```
error /foo/node_modules/@mlink/scrypt: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /foo/node_modules/@mlink/scrypt
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.15.1 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/foo/.nvm/versions/node/v8.15.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/foo/node_modules/@mlink/scrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/foo/.nvm/versions/node/v8.15.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/foo/.node-gyp/8.15.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/foo/.node-gyp/8.15.1',
gyp info spawn args   '-Dnode_gyp_dir=/foo/.nvm/versions/node/v8.15.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/foo/.node-gyp/8.15.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/foo/node_modules/@mlink/scrypt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  LIBTOOL-STATIC Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.1/lib/crypto/crypto_scrypt.o
In file included from ../scrypt/scrypt-1.2.1/lib/crypto/crypto_scrypt.c:29:
../scrypt/scrypt-1.2.1/scrypt_platform.h:7:10: fatal error: 'config.h' file not found
#include "config.h"
         ^~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.1/lib/crypto/crypto_scrypt.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/foo/.nvm/versions/node/v8.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/foo/.nvm/versions/node/v8.15.1/bin/node" "/foo/.nvm/versions/node/v8.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /foo/node_modules/@mlink/scrypt
gyp ERR! node -v v8.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by ml1nk** [comment]
"config.h" should be generated in "node-scrypt-preinstall.js" by "./configure". Is there an error before this one?

**Comment by gabegorelick** [comment]
```
> @mlink/scrypt@6.1.2 preinstall /foo/node_modules/@mlink/scrypt
> node node-scrypt-preinstall.js

Error: Error: Command failed: ./configure
configure: error: function AES_ENCRYPT not found
```

Running LibreSSL 2.6.5 on macOS 10.14.4.

**Comment by ml1nk** [comment]
You are missing a dependency like in [issue 6](https://github.com/ml1nk/node-scrypt/issues/6) which was introduced by scrypt 1.2.1. 

> Have you installed openssl-dev (Ubuntu: "sudo apt-get install libssl-dev")?
